baseurl = "https://anyplace2030.work/"
title = "黄金の未来の探し方"
theme = "hugo_theme_robust"

googleAnalytics = "UA-11961133-25" # Optional
disqusShortname = "XYW"

[params]
description = "マイクロビジネスのアイディアを紹介するサイト"
dateformat = "Jan 2, 2006" # Optional
# Fonts settings.
googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
thumbnail = "images/author.jpg"
name = "Yohei Tanaka"
description = '<p>マイクロビジネス研究家<br>マレーシア在住ベトナムハノイに出張多数<br>世界の股にかけるプログラマー上がりのブリッジSE<br>8歳の女の子の父親</p><a href="/pages/about/">本サイトの紹介と私のプロフィールはこちら</a>'
#facebook = "https://www.facebook.com/daisuke.tsuji.735"
twitter = "https://twitter.com/tanakayohei3"
#github = "https://github.com/dim0627"
#instagram = "https://www.instagram.com/you19782000/"

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.

[menu]
 [[menu.main]]
    identifier = "aboutme"
    name = "About me"
    title = "blog section"
    url = "/pages/about/"
    weight = -110

 [[menu.main]]
    identifier = "blog"
    name = "ブログ"
    title = "blog section"
    url = "/post/"
    weight = -110