
baseurl = "https://anyplace2030.work/"
title = "STEPNの日々"
languageCode = "ja"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-11961133-25" # Enable Google Analytics by entering your tracking id

[Author]
  name = "よーへい"  
  bio = "投機で大損した経験から立ち直り楽しくSTEPをするサイトを運営。福岡を在住。サラリーマンリモートワーカー。11歳の女の子の父親。現在STEPNを検証中！"
  avatar = "images/author.jpg"

[markup.goldmark.parser.attribute]
  block = true

[Params]
  subtitle = "黄金の未来の探し方" # Subtitle of your site
  description = "福岡を拠点にしたリモートワークプログラマーサラリーマンが安全にSTEPNをするサイト！" # Description of your site
  opengraph = true
  twitter_cards = true
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  post_navigation = true
  post_meta = ["date", "categories"] # Order of post meta information
  toc = true
  customCSS = ["/css/custom.css"]
  ##highlightColor = "#ffb107" # Override highlight color

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["authorbox", "search", "social", "amazon","recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  #facebook = "username"
  twitter = "fireCodeCoin"
  #instagram = "username"
  #linkedin = "username"
  #telegram = "username"
  #github = "you1978"
  #gitlab = "username"
  #bitbucket = "username"
  #email = "you1978@hotmail.com"

[[Params.widgets.social.custom]]
  title = "問合せフォーム"
  url = "/pages/contactus/"

# [[Params.widgets.social.custom]]
#   title = "note"
#   url = "https://note.com/you1978"

[[Params.widgets.social.custom]]
  title = "Line"
  url = "https://lin.ee/s3Ji7QW"

[menu]
 [[menu.main]]
    identifier = "aboutme"
    name = "自己紹介"
    title = "blog section"
    url = "/pages/about/"
    weight = 0

   [[menu.main]]
    identifier = "code"
    name = "STEPNを始める"
    title = "blog section"
    url = "/post/code"
    weight = -100

    [[menu.main]]
    identifier = "earn"
    name = "STEPNで稼ぐ"
    title = "blog section"
    url = "/post/earn"
    weight = -90

    [[menu.main]]
    identifier = "learn"
    name = "STEPNを学ぶ"
    title = "blog section"
    url = "/post/learn"
    weight = -80

    [[menu.main]]
    identifier = "check"
    name = "収支を見る"
    title = "blog section"
    url = "/post/report"
    weight = -70

#  [[menu.main]]
#     identifier = "blog"
#     name = "ブログ"
#     title = "blog section"
#     url = "/post/blog"
#     weight = -110

  # [[menu.main]]
  #   identifier = "invest"
  #   name = "投資"
  #   title = "invest section"
  #   url = "/post/invest"
  #   weight = -100

  # [[menu.main]]
  #   identifier = "earn"
  #   name = "稼ぐ方法"
  #   title = "earn section"
  #   url = "/post/earn"
  #   weight = -90

#  [[menu.main]]
#    identifier = "seo"
#    name = "SEO実験室"
#    title = "seo section"
#    url = "/post/seo"
#    weight = -30

  # [[menu.main]]
  #   identifier = "code"
  #   name = "仮想通貨"
  #   title = "code section"
  #   url = "/post/code"
  #   weight = -30

  # [[menu.main]]
  #   identifier = "living"
  #   name = "新生活"
  #   title = "New Living"
  #   url = "/post/live"
  #   weight = -20

#  [[menu.main]]
#    identifier = "programing"
#    name = "プログラミング"
#    title = "programing section"
#    url = "/post/programing"
#    weight = -10
