
baseurl = "https://anyplace2030.work/"
title = "セミリタイアを目指すプログラマーのブログ"
languageCode = "ja"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-11961133-25" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Yohei Tanaka"  
  bio = "マイクロビジネス研究家。福岡在住ベトナムハノイに出張多数。世界の股にかけるプログラマー上がりのブリッジSE。8歳の女の子の父親"
  avatar = "images/author.jpg"

[Params]
  subtitle = "黄金の未来の探し方" # Subtitle of your site
  description = "福岡在住のリモートワークプログラマーサラリーマンがセミリタイアを目指すための過程を書いたブログ！" # Description of your site
  opengraph = true
  twitter_cards = true
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  post_navigation = true
  post_meta = ["date", "categories"] # Order of post meta information
  toc = true
  customCSS = ["/css/custom.css"]

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["authorbox", "search", "amazon", "social","recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  #facebook = "username"
  twitter = "tanakayohei3"
  #instagram = "username"
  #linkedin = "username"
  #telegram = "username"
  github = "you1978"
  #gitlab = "username"
  #bitbucket = "username"
  email = "you1978@hotmail.com"

[[Params.widgets.social.custom]]
  title = "note"
  url = "https://note.com/you1978"

[menu]
 [[menu.main]]
    identifier = "aboutme"
    name = "自己紹介"
    title = "blog section"
    url = "/pages/about/"
    weight = 0

 [[menu.main]]
    identifier = "blog"
    name = "ブログ"
    title = "blog section"
    url = "/post/blog"
    weight = -110

  [[menu.main]]
    identifier = "invest"
    name = "投資"
    title = "invest section"
    url = "/post/invest"
    weight = -100

  [[menu.main]]
    identifier = "earn"
    name = "稼ぐ方法"
    title = "earn section"
    url = "/post/earn"
    weight = -90

  [[menu.main]]
    identifier = "seo"
    name = "SEO実験室"
    title = "seo section"
    url = "/post/seo"
    weight = -30

  [[menu.main]]
    identifier = "living"
    name = "新生活"
    title = "New Living"
    url = "/post/live"
    weight = -20

  [[menu.main]]
    identifier = "micro"
    name = "世界のマイクロビジネス紹介"
    title = "microbusiness section"
    url = "/post/micro"
    weight = -10